### ISSUE TITLE
00005: Numéro de question invalide - Increase timeout between first and secondary requests

### ISSUE THREAD

**Issue by veacks** [arambert/Paybox-Direct-Plus#11]
Hi,

We have sometimes a "00005: Numéro de question invalide" response error when the payment have been set as succeed.

After digging in Paybox logs with Paybox support, we figured out that the problem come from the timeout of the first request to ppps.paybox.com which isn't waiting for 30s at least to call another request to ppps1.paybox.com which is trying to perform the same payment again.

The first request to ppps.paybox.com is succeed.
The second request to pps1.paybox.com have the error "00005: Numéro de question invalide" because already treated by the first request.

My question is, how can I increase the timeout of the first request?

Thanks for any help, and btw thanks for your plugin.

**Comment by arambert** [comment]
Hi,

This is handled by the gateway paybox_direct: https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/paybox_direct.rb#L153

As far as I can see there is no way to set a delay after the first response without altering the current code:

        response = parse(ssl_post(test? ? self.test_url : self.live_url, request_data))
        response = parse(ssl_post(self.live_url_backup, request_data)) if service_unavailable?(response) && !test?

You may open an issue at https://github.com/activemerchant/active_merchant regarding Paybox Direct or better even create a Pull Request with the relevant edits & corresponding tests.

**Comment by veacks** [comment]
Hi @arambert, 
Sorry, I just came across your answer.
We will see with active_merchant.
Thank you for your time.
